# Generated by Django 4.2.15 on 2024-08-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactorCalssInfo',
            fields=[
                ('FactorCalssID', models.AutoField(primary_key=True, serialize=False)),
                ('FactorCalssName', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FactorInfo',
            fields=[
                ('FactorID', models.AutoField(primary_key=True, serialize=False)),
                ('FactorName', models.CharField(blank=True, max_length=64, null=True)),
                ('FactorCalssID', models.IntegerField(blank=True, null=True)),
                ('FactorNum', models.FloatField(blank=True, null=True)),
                ('FactorUnit', models.CharField(blank=True, max_length=64, null=True)),
                ('FactorSource', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormulaInfo',
            fields=[
                ('FormulaID', models.AutoField(primary_key=True, serialize=False)),
                ('cement', models.FloatField(blank=True, null=True)),
                ('GBFS', models.FloatField(blank=True, null=True)),
                ('FA', models.FloatField(blank=True, null=True)),
                ('water', models.FloatField(blank=True, null=True)),
                ('FAggregate', models.FloatField(blank=True, null=True)),
                ('CAggregate', models.FloatField(blank=True, null=True)),
                ('Superplasticizer', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StrengthInfo',
            fields=[
                ('StrengID', models.AutoField(primary_key=True, serialize=False)),
                ('FormulaID', models.IntegerField(blank=True, null=True)),
                ('age', models.FloatField(blank=True, null=True)),
                ('Strength', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('UID', models.AutoField(primary_key=True, serialize=False)),
                ('User', models.CharField(blank=True, max_length=64, null=True)),
                ('Pass', models.CharField(blank=True, max_length=64, null=True)),
                ('Mail', models.CharField(blank=True, max_length=64, null=True)),
                ('authority', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
