# Generated by Django 4.2.15 on 2024-08-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbonwebapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelsInfo',
            fields=[
                ('ModelID', models.AutoField(primary_key=True, serialize=False)),
                ('ModelName', models.CharField(blank=True, max_length=64, null=True)),
                ('Modelpath', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
