# Generated by Django 4.2.15 on 2024-08-30 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbonwebapp', '0002_modelsinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsinfo',
            name='Modelpath',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
