# Generated by Django 4.2.15 on 2024-09-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbonwebapp', '0003_alter_modelsinfo_modelpath'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaCompareInfo',
            fields=[
                ('CompareID', models.AutoField(primary_key=True, serialize=False)),
                ('OptimizeID', models.IntegerField(blank=True, null=True)),
                ('FormulaID', models.IntegerField(blank=True, null=True)),
                ('FormulaPrice', models.FloatField(blank=True, null=True)),
                ('carbonFormula', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptimizeInfo',
            fields=[
                ('OptimizeID', models.AutoField(primary_key=True, serialize=False)),
                ('TargetDay', models.FloatField(blank=True, null=True)),
                ('TargetStrength', models.FloatField(blank=True, null=True)),
                ('TargetSlump', models.FloatField(blank=True, null=True)),
                ('bestCost', models.FloatField(blank=True, null=True)),
                ('bestCarbon', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
