# Generated by Django 4.2.15 on 2024-09-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbonwebapp', '0004_formulacompareinfo_optimizeinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizeinfo',
            name='bestCarbonFormulaID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='optimizeinfo',
            name='bestCostFormulaID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
