# Generated by Django 4.2.15 on 2024-09-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbonwebapp', '0005_optimizeinfo_bestcarbonformulaid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='carbonInfo',
            fields=[
                ('OptimizeID', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.CharField(blank=True, max_length=128, null=True)),
                ('cement', models.FloatField(blank=True, null=True)),
                ('GBFS', models.FloatField(blank=True, null=True)),
                ('FA', models.FloatField(blank=True, null=True)),
                ('water', models.FloatField(blank=True, null=True)),
                ('FAggregate', models.FloatField(blank=True, null=True)),
                ('CAggregate', models.FloatField(blank=True, null=True)),
                ('Superplasticizer', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceInfo',
            fields=[
                ('OptimizeID', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.CharField(blank=True, max_length=128, null=True)),
                ('cement', models.FloatField(blank=True, null=True)),
                ('GBFS', models.FloatField(blank=True, null=True)),
                ('FA', models.FloatField(blank=True, null=True)),
                ('water', models.FloatField(blank=True, null=True)),
                ('FAggregate', models.FloatField(blank=True, null=True)),
                ('CAggregate', models.FloatField(blank=True, null=True)),
                ('Superplasticizer', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
